### ISSUE TITLE
Errors Appearing Outside of Target App Screenshot

### ISSUE THREAD

**Issue by daphneyyt** [microsoft/accessibility-insights-for-android-service#67] opened 2020-12-24 05:04 UTC
Hi GitHub

We are scanning the mobile apps on Accessibility Insight For Android. We are encountering issues where there are errors flagged outside of the mobile app (see Target app screenshot attached, highlighted in cyan). 
<img width="516" alt="Target App Screenshot" src="https://user-images.githubusercontent.com/75086091/103062081-2dea6f80-45e8-11eb-904f-3467f757993c.png">

However, there are no further details outside the screen. May I know what is causing these flagged errors to appear?

If it helps, these are the element paths raised by the software for your reference (WCAG 1.3.1, 3.3.2).
1. android.widget.TextView
2. androidx.appcompat.app.ActionBar$Tab
3. android.widget.LinearLayout
4. android.widget.ImageButton
5. android.widget.ImageView
6. android.view.View

Thank you!
Daphne

**Comment by karanbirsingh** [comment] 2020-12-28 18:12
Thanks for reporting the issue, @daphneyyt! To dig deeper we will need to reproduce the issue. Can you share the following info to help us?
- What device/emulator version are you using?
- What target app are you testing?
- Has the device/emulator view been modified (e.g. is magnification on?)

**Comment by daphneyyt** [comment] 2020-12-29 02:19
Thank you for reaching out, @karanbirsingh 

Please find my response below:

**1. What device/emulator version are you using?**
Device:
the app is tested on:
- Galaxy A51 phone, Android version 10 
- OPPO R11S, Android version 7.1.1

Emulator:
- we are using Accessibility Insights For Android (windows), version v2020.1124.4.
- however, this issue was also present when the emulator version was at version v2020.909.5

**2. What target app are you testing?**
- we were testing for WCAG 1.1.1 and WCAG 1.3.1/ 3.3.2

**3. Has the device/emulator view been modified (e.g. is magnification on?)**
- I am not too sure what do you mean by this question, but we have been using Accessibility Insights For Android as it is (no adjustments to default settings)

I hope the above clarifies. Thank you!

A 2nd question which I have that is unrelated to the question I posted originally is that there some errors that have highlights unavailable. May I know what triggers this as well? 
<img width="452" alt="wcag 131, 332" src="https://user-images.githubusercontent.com/75086091/103254174-4af3b980-49bf-11eb-8df3-643fbcafbbc8.png">

**Comment by karanbirsingh** [comment] 2020-12-29 05:51
Thanks @daphneyyt - if I understand right, you're saying you test using physical devices (Galaxy + OPPO). What Android app are you testing? It would be helpful for us to download & try on our side.

**Comment by daphneyyt** [comment] 2020-12-29 09:21
Hi @karanbirsingh yes we tested the app with physical devices Samsung / Oppo

This is the app we tested:
https://play.google.com/store/apps/details?id=com.ministryofhomeaffairs.sgsecure.mhasg&hl=en_SG&gl=US

The landing screen upon app launch will show this issue. Thank you!

**Comment by karanbirsingh** [comment] 2020-12-30 00:05
Thanks @daphneyyt - I tried the app and can reproduce this on my side too.

Accessibility Insights [relies](https://github.com/microsoft/accessibility-insights-for-android-service/blob/a5462d83e27146e5ef1d05815dea3fa442d5208e/AccessibilityInsightsForAndroidService/app/src/main/java/com/microsoft/accessibilityinsightsforandroidservice/NodeViewBuilder.java#L94) on the [getBoundsInScreen API](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#getBoundsInScreen(android.graphics.Rect)) to know where to draw elements. When we ask the Android app for its element positions, it looks like some of the returned dimensions are offscreen. For instance, the screen bounds are 1920 x 1080, but some elements have rectangles like `["bottom": 1794, "left": 1080, "right": 4149, "top": 1636 ]`. Because `left` and `right` range from `1080` to `4149`, the rectangle is to the right of the screenshot.

> A 2nd question which I have that is unrelated to the question I posted originally is that there some errors that have highlights unavailable. May I know what triggers this as well?

This is the same cause (offscreen rectangles) but it seems we currently [filter out 'negative' bounds](https://github.com/microsoft/accessibility-insights-web/blob/01ab87889df961d739d3c06e53860bb2906efeeb/src/common/is-result-highlight-unavailable.ts#L31). Instead of drawing them on the screen, the tool says 'highlight unavailable'. This explains why the offscreen errors never appear to the left of the target app screenshot. 

We can't change the rectangles provided from the Android app to Accessibility Insights, but we should investigate how to best visualize the cases you shared (e.g. filter them out as well, add some help text, etc).

I will mark this issue 'ready for triage' so we can discuss this further when folks are in. I have compiled logs [sgsecure-logs.zip](https://github.com/microsoft/accessibility-insights-for-android-service/files/5752582/sgsecure-logs.zip) that show the [`isOffScreen` property](https://github.com/dequelabs/axe-android/blob/2b56372a39b568b6fb4acba4d727e62b6ec94681/src/main/java/com/deque/axe/android/AxeView.java#L521) provided by `axe-android`.

**Comment by daphneyyt** [comment] 2020-12-30 05:24
Hi @karanbirsingh thank you very much for the explanation and feedback as to what is causing this issue! Appreciate it! Wishing you and your team happy new year and a great 2021 ahead.

**Comment by ferBonnin** [comment] 2021-01-04 21:24
To summarize our conversation:

- We should look into filtering out this from the screenshot 
- We will look into if its needed to update the documentation in accessibilityinsights.io to be very clear about why a highlight is unavailable.

**Comment by DaveTryon** [comment] 2023-05-11 20:52
As called out at https://github.com/microsoft/accessibility-insights-for-android-service#notice, we will not be making further investments in the Android scanning solution. As such, we're closing this out.

Thanks for your interest in Accessibility Insights!

**Closed by DaveTryon** 2023-05-11 20:52 UTC
Labels: feature request, status: ready for work
