### ISSUE TITLE
Advice Needed For WCAG 1.3.1, WCAG 3.3.2 (ActiveViewName) Fix

### ISSUE THREAD

**Issue by daphneyyt** [microsoft/accessibility-insights-for-android-service#103] opened 2021-06-02 07:19 UTC
Dear Accessibility Insights team

We are trying to fix the accessibility issue: WCAG 1.3.1, WCAG 3.3.2 (ActiveViewName) identified by Accessibility Insights For Android (see screenshot below).

![image](https://user-images.githubusercontent.com/75086091/120438129-8c93f080-c3b3-11eb-8081-88371c9a3e3a.png)

We have tried to address the issue by providing a description for the ActiveView (see the link for our output in video form below).

[https://drive.google.com/file/d/1jSAUhIGyFlP3gnarUKv9_bDjsIeo0bQM/view?usp=sharing](url)

However, the issue is still flagged by Accessibility Insights For Android.

May we know: 
1) Why is the WCAG issue still flagged by Accessibility Insights For Android?

2) What have we not done correctly for the fix, and what should we do to correct it?

Greatly appreciate your assistance with this! Thank you.

**Comment by karanbirsingh** [comment] 2021-06-02 23:35
Hi @daphneyyt it would be easier to investigate with a link to the application and/or source code. Is this something you're able to provide? Thank you!

**Comment by daphneyyt** [comment] 2021-06-03 08:36
Hi @karanbirsingh thank you for getting back to us. We are checking in with the team in charge if they could get in touch with you directly to provide the details you require. We will update you on this. Thank you!

**Comment by salimgcet** [comment] 2021-06-04 06:46
Hello Team,

The feedback page is an HTML page, and we are using the below code snippet.
When we enable the screen reader from accessibility settings, the screen reader reads the content correctly.


<ul class="section-your-contact" aria-labelledby="labelContact">
						<li>
							<label for="name">Name*:</label>
							**<input autocomplete='name' class="text" type="text" name="name" id="name" aria-label="Enter your name"/>**
						</li>
				
					</ul>

Appreciate your assistance with this.

**Comment by salimgcet** [comment] 2021-06-07 07:48
Hello Team,

Appreciate your assistance on the above queries.

Thanks.

**Comment by karanbirsingh** [comment] 2021-06-07 23:13
Hi @salimgcet - for HTML pages we usually recommend running [Accessibility Insights for Web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni) since its use of `axe-core` will provide the most accurate results for HTML content. Rules tuned for the DOM will be more accurate for the HTML parts of your application.

Can you share how the HTML code is leveraged in your Android application - is it a `WebView`?

**Comment by salimgcet** [comment] 2021-06-08 01:07
Hello Karan,

Thanks for the update.

Yes, we are using web view for the Feedback page.

**Comment by karanbirsingh** [comment] 2021-06-09 23:08
Thanks @salimgcet! I recommend using a web-based testing tool like Accessibility Insights for Web to test the HTML parts of your application separately. Resolving any issues it finds will be the best approach to improving the website accessibility.

We can look closer at the issues that Accessibility Insights for Android finds in web-based content; it's possible that assistive technologies could have first-class support for the HTML in a webview, so the ActiveViewName may be ignored. The best way to explore this is running AI-Web on the page in your WebView. We will explore whether we can reproduce this case in a sample application with a WebView; if a web page has no AI-Web fastpass errors but still produces an ActiveViewName error, we may consider amending the ruleset.

**Comment by DaveTryon** [comment] 2023-05-11 20:54
As called out at https://github.com/microsoft/accessibility-insights-web#notice, we will not be making further investments in the Android scanning solution. As such, we're closing this out.

Thanks for your interest in Accessibility Insights!

**Closed by DaveTryon** 2023-05-11 20:54 UTC
Labels: status: needs investigation
